// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4jzDhpPXSPGepcOxQawgEYNfYAPV6izI',
    appId: '1:1019615256238:web:0f990ceb3b770e986c173f',
    messagingSenderId: '1019615256238',
    projectId: 'login-equiporobles-d9bfa',
    authDomain: 'login-equiporobles-d9bfa.firebaseapp.com',
    storageBucket: 'login-equiporobles-d9bfa.firebasestorage.app',
    measurementId: 'G-BR7TC2R6CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3-Zdlqu6f8UCCvmbO3vbZg0_qvuZlfE',
    appId: '1:1019615256238:android:930e530752a72d986c173f',
    messagingSenderId: '1019615256238',
    projectId: 'login-equiporobles-d9bfa',
    storageBucket: 'login-equiporobles-d9bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmoMhiVF2KCvjE3DuErmn4qzR6f32KdjY',
    appId: '1:1019615256238:ios:ea2bdf80c2995a196c173f',
    messagingSenderId: '1019615256238',
    projectId: 'login-equiporobles-d9bfa',
    storageBucket: 'login-equiporobles-d9bfa.firebasestorage.app',
    iosBundleId: 'com.example.loginEquiporobles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmoMhiVF2KCvjE3DuErmn4qzR6f32KdjY',
    appId: '1:1019615256238:ios:ea2bdf80c2995a196c173f',
    messagingSenderId: '1019615256238',
    projectId: 'login-equiporobles-d9bfa',
    storageBucket: 'login-equiporobles-d9bfa.firebasestorage.app',
    iosBundleId: 'com.example.loginEquiporobles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4jzDhpPXSPGepcOxQawgEYNfYAPV6izI',
    appId: '1:1019615256238:web:5b6efd028301b5336c173f',
    messagingSenderId: '1019615256238',
    projectId: 'login-equiporobles-d9bfa',
    authDomain: 'login-equiporobles-d9bfa.firebaseapp.com',
    storageBucket: 'login-equiporobles-d9bfa.firebasestorage.app',
    measurementId: 'G-PCE1TZM45N',
  );
}
